angular.module('app')
	.controller('classifyController',["$scope",function($scope){
		$scope.data=[
		{
			dataImg:'./images/banner4.png'
		}
		];
		$scope.Health_products=[
		{
			first:'热销推选',
			hot:'最热',
			fllown:'趁火打劫都带走我们！'
		}
		];
		$scope.list=[
		{
			furnace:'电磁炉',
			furnaceImg:'./images/classify1.png',
			HealthCare:'养生煲',
			HealthCareImg:'./images/classify2.png',
			beanImg:'./images/classify3.png',
			bean:'豆浆机'
		},
		{
			furnace:'绞肉机',
			furnaceImg:'./images/classify4.png',
			HealthCare:'榨汁机',
			HealthCareImg:'./images/classify5.png',
			beanImg:'./images/classify6.png',
			bean:'压力锅'
		},
		{
			furnace:'自能化',
			furnaceImg:'./images/classify7.png',
			HealthCare:'白瓷煲',
			HealthCareImg:'./images/classify8.png',
			beanImg:'./images/classify9.png',
			bean:'泡汤机'
		}
		]
	}])